# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lisette',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/lisette',
                'lib_path': 'lisette'},
  'syms': {'lisette.core': {'lisette.core.foo': ('core.html#foo', 'lisette/core.py')}}}
